networks:
  etcd_net:
    external: true
    name: etcd_net
services:
  etcd1: 
    image: quay.io/coreos/etcd:v3.6.7
    command: >
      /usr/local/bin/etcd
      --name=etcd1
      --data-dir=/data
      --listen-client-urls=http://0.0.0.0:2379
      --advertise-client-urls=http://etcd1:2379
      --listen-peer-urls=http://0.0.0.0:2380
      --initial-advertise-peer-urls=http://etcd1:2380
      --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      --initial-cluster-state=new
      --initial-cluster-token=api_gateway_cluster
    volumes:
      - etcd1_data:/data
    networks:
      - etcd_net

  etcd2:
    image: quay.io/coreos/etcd:v3.6.7
    command: >
      /usr/local/bin/etcd
      --name=etcd2
      --data-dir=/data
      --listen-client-urls=http://0.0.0.0:2379
      --advertise-client-urls=http://etcd2:2379
      --listen-peer-urls=http://0.0.0.0:2380
      --initial-advertise-peer-urls=http://etcd2:2380
      --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      --initial-cluster-state=new
      --initial-cluster-token=api_gateway_cluster
    volumes:
      - etcd2_data:/data
    networks:
      - etcd_net

  etcd3:
    image: quay.io/coreos/etcd:v3.6.7
    command: >
      /usr/local/bin/etcd
      --name=etcd3
      --data-dir=/data
      --listen-client-urls=http://0.0.0.0:2379
      --advertise-client-urls=http://etcd3:2379
      --listen-peer-urls=http://0.0.0.0:2380
      --initial-advertise-peer-urls=http://etcd3:2380
      --initial-cluster=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380
      --initial-cluster-state=new
      --initial-cluster-token=api_gateway_cluster
    volumes:
      - etcd3_data:/data
    networks:
      - etcd_net


volumes:
  etcd1_data:
     driver: local
  etcd2_data:
     driver: local
  etcd3_data:
     driver: local