networks:
  postgres_follow_net:
    driver: bridge
  app_net:
    driver: bridge
  common_net:
    external: true
    name: common_network
  etcd_net:
    external: true
    name: etcd_net

services:
  follow-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: follow_service:1.0.0
    env_file:
      - .follow.env
    networks:
      - app_net
      - postgres_follow_net
      - common_net
      - etcd_net
    depends_on:
      - postgres_follow_primary
      - postgres_follow_secondary

  postgres_follow_primary:
    image: postgres:17
    container_name: postgres_follow_primary
    env_file:
      - .primary.env
    volumes:
      - primary_follow_data:/var/lib/postgresql/data
      - ./primary_init:/docker-entrypoint-initdb.d
    networks:
      - postgres_follow_net
      - app_net

  postgres_follow_secondary:
    image: postgres:17
    container_name: postgres_follow_secondary
    env_file:
      - .replica.env
    volumes:
      - secondary_follow_data:/var/lib/postgresql/data
      - ./secondary_init:/docker-entrypoint-initdb.d
    networks:
      - postgres_follow_net
      - app_net
    restart: on-failure:3
volumes:
  primary_follow_data:
    driver: local
  secondary_follow_data:
    driver: local