
#user
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: userx-db-credentials
  namespace: dmb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: userx-db-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        db_name: "{{ .db_name }}"
        port: "{{ .port }}"
        primary_host: "{{ .primary_host }}"
        replica_host: "{{ .replica_host }}"
        PRIMARY_DB_URL: "jdbc:postgresql://{{ .primary_host }}:{{ .port }}/{{ .db_name }}"
        SECONDARY_DB_URL: "jdbc:postgresql://{{ .replica_host }}:{{ .port }}/{{ .db_name }}"
  dataFrom:
    - extract:
        key: tf-dmb-dev/userx/db-credentials


# post
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: post-db-credentials
  namespace: dmb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: post-db-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        db_name: "{{ .db_name }}"
        port: "{{ .port }}"
        primary_host: "{{ .primary_host }}"
        replica_host: "{{ .replica_host }}"
        PRIMARY_DB_URL: "jdbc:postgresql://{{ .primary_host }}:{{ .port }}/{{ .db_name }}"
        SECONDARY_DB_URL: "jdbc:postgresql://{{ .replica_host }}:{{ .port }}/{{ .db_name }}"
  dataFrom:
    - extract:
        key: tf-dmb-dev/post/db-credentials


# follow
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: follow-db-credentials
  namespace: dmb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: follow-db-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        db_name: "{{ .db_name }}"
        port: "{{ .port }}"
        primary_host: "{{ .primary_host }}"
        replica_host: "{{ .replica_host }}"
        PRIMARY_DB_URL: "jdbc:postgresql://{{ .primary_host }}:{{ .port }}/{{ .db_name }}"
        SECONDARY_DB_URL: "jdbc:postgresql://{{ .replica_host }}:{{ .port }}/{{ .db_name }}"
  dataFrom:
    - extract:
        key: tf-dmb-dev/follow/db-credentials
