apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: userx-db-credentials
  namespace: dmb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: userx-db-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        db_name: "{{ .db_name }}"
        port: "{{ .port }}"
        primary_host: "{{ .primary_host }}"
        replica_host: "{{ .replica_host }}"
        PRIMARY_DB_URL: "jdbc:postgresql://{{ .primary_host }}:{{ .port }}/{{ .db_name }}"
        SECONDARY_DB_URL: "jdbc:postgresql://{{ .replica_host }}:{{ .port }}/{{ .db_name }}"
  dataFrom:
    - extract:
        # TODO:
        # THis will work for dev env now 
        # Make the key-prefix dynamic per env
        # Look at kustomization //
        key: tf-dmb-dev/userx/db-credentials  


# post
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: post-db-credentials
  namespace: dmb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: post-db-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        db_name: "{{ .db_name }}"
        port: "{{ .port }}"
        primary_host: "{{ .primary_host }}"
        replica_host: "{{ .replica_host }}"
  dataFrom:
    - extract:
        key: tf-dmb-dev/post/db-credentials


# follow
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: follow-db-credentials
  namespace: dmb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: follow-db-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        db_name: "{{ .db_name }}"
        port: "{{ .port }}"
        primary_host: "{{ .primary_host }}"
        replica_host: "{{ .replica_host }}"
        PRIMARY_DB_URL: "jdbc:postgresql://{{ .primary_host }}:{{ .port }}/{{ .db_name }}"
        SECONDARY_DB_URL: "jdbc:postgresql://{{ .replica_host }}:{{ .port }}/{{ .db_name }}"
  dataFrom:
    - extract:
        key: tf-dmb-dev/follow/db-credentials

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-gateway-cache-credentials
  namespace: dmb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: api-gateway-cache-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ELASTICACHE_CLUSTER_ENDPOINT: "{{ .cluster_endpoint }}:{{ .cluster_port }}"
        ELASTICACHE_STANDALONE_ENDPOINT: "{{ .standalone_endpoint }}:{{ .standalone_port }}"
  dataFrom:
    - extract:
        key: tf-dmb-dev/api-gateway/cache-credentials

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: post-cache-credentials
  namespace: dmb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: post-cache-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ELASTICACHE_CLUSTER_ENDPOINT: "{{ .cluster_endpoint }}:{{ .cluster_port }}"
        ELASTICACHE_CLUSTER_PASSWORD: "{{ .cluster_password}}"
  dataFrom:
    - extract:
        key: tf-dmb-dev/post/cache-credentials

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: feed-cache-credentials
  namespace: dmb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: feed-cache-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ELASTICACHE_CLUSTER_ENDPOINT: "{{ .cluster_endpoint }}:{{ .cluster_port }}"
        ELASTICACHE_CLUSTER_PASSWORD: "{{ .cluster_password}}"
  dataFrom:
    - extract:
        key: tf-dmb-dev/feed/cache-credentials

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: userx-cache-credentials
  namespace: dmb
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: userx-cache-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ELASTICACHE_STANDALONE_ENDPOINT: "{{ .standalone_endpoint }}"
        ELASTICACHE_STANDALONE_PORT: "{{ .standalone_port }}"
        ELASTICACHE_STANDALONE_PASSWORD: "{{ .standalone_password}}"
        ELASTICACHE_CLUSTER_ENDPOINT: "{{ .cluster_endpoint }}:{{ .cluster_port }}"
  dataFrom:
    - extract:
        key: tf-dmb-dev/userx/cache-credentials
